module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  biz_iamlobbyist: 0
  biz_lobbyist_registration: 0
  biz_webforms: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  button_link: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  config_translation: 0
  config_update: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_reference_revisions: 0
  external_db_login: 0
  external_entities: 0
  facets: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  help: 0
  hierarchical_multi_select: 0
  hierarchical_taxonomy_menu: 0
  history: 0
  http_client_manager: 0
  image: 0
  kint: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_st: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  lightning_core: 0
  link: 0
  locale: 0
  mask: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  multiple_registration: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  rest: 0
  rest_register_verify_email: 0
  restui: 0
  rules: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  select2: 0
  select2_facets: 0
  serialization: 0
  shortcut: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  telephone_formatter: 0
  telephone_validation: 0
  term_csv_export_import: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_fieldsets: 0
  views_ui: 0
  webform: 0
  webform_composite: 0
  webform_devel: 0
  webform_node: 0
  webform_rest: 0
  webform_ui: 0
  wxt_library: 0
  menu_link_content: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  wxt_bootstrap: 0
  wxt_lobbyist: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
