address: 1.7.0
admin_toolbar: 1.27.0
admin_toolbar_tools: 1.27.0
automated_cron: 8.7.8
big_pipe: 8.7.8
biz_iamlobbyist: '1'
biz_lobbyist_registration: '1'
block: 8.7.8
block_class: 1.0.0
block_content: 8.7.8
bootstrap_layouts: 5.1.0
breakpoint: 8.7.8
button_link: 1.1.0
ckeditor: 8.7.8
color: 8.7.8
comment: 8.7.8
config: 8.7.8
config_direct_save: 1.0.0
config_translation: 8.7.8
config_update: 1.6.0
contact: 8.7.8
content_translation: 8.7.8
contextual: 8.7.8
ctools: 3.2.0
ctools_block: 3.2.0
ctools_views: 3.2.0
datetime: 8.7.8
dblog: 8.7.8
devel: 2.1.0
dynamic_page_cache: 8.7.8
editor: 8.7.8
email_registration: 1.0.0-rc7
entity_block: 1.0.0-beta1
entity_reference_revisions: 1.7.0
features: 3.8.0
features_ui: 3.8.0
field: 8.7.8
field_group: 3.0.0-rc1
field_ui: 8.7.8
file: 8.7.8
filter: 8.7.8
help: 8.7.8
history: 8.7.8
http_client_manager: 2.3.0
image: 8.7.8
kint: 2.1.0
language: 8.7.8
layout_builder: 8.7.8
layout_builder_restrictions: 2.2.0
layout_builder_st: 1.0.0-alpha1
layout_builder_styles: 1.0.0-beta1
layout_discovery: 8.7.8
layout_library: 1.0.0-beta1
lightning_core: 4.7.0
link: 8.7.8
locale: 8.7.8
mask: 1.0.0-alpha2
media: 8.7.8
media_library: 8.7.8
menu_block: 1.5.0
menu_link_content: 8.7.8
menu_ui: 8.7.8
multiple_registration: 2.87.0
node: 8.7.8
options: 8.7.8
page_cache: 8.7.8
path: 8.7.8
quickedit: 8.7.8
rdf: 8.7.8
rest: 8.7.8
restui: 1.17.0
rules: 3.0.0-alpha5
search: 8.7.8
serialization: 8.7.8
shortcut: 8.7.8
standard: 8.7.8
system: 8.7.8
taxonomy: 8.7.8
telephone: 8.7.8
telephone_formatter: 1.0.0
telephone_validation: 2.2.0
text: 8.7.8
token: 1.5.0
toolbar: 8.7.8
tour: 8.7.8
twig_tweak: 2.4.0
typed_data: 1.0.0-alpha3
update: 8.7.8
user: 8.7.8
views: 8.7.8
views_ui: 8.7.8
webform: 5.5.0
webform_bootstrap: 5.5.0
webform_composite: 0.0.0
webform_devel: 5.5.0
webform_rest: 0.0.0
webform_ui: 5.5.0
wxt_library: 1.10.0
